framework:
    rate_limiter:
        limiters:
            anonymous_api:
                policy: 'token_bucket'
                limit: 60
                rate: { interval: '1 minute' }

            authenticated_api:
                policy: 'token_bucket'
                limit: 120
                rate: { interval: '1 minute' }

when@test:
    framework:
        rate_limiter:
            limiters:
                anonymous_api: { policy: 'no_limit' }
                authenticated_api: { policy: 'no_limit' }
