controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
redirect_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login
        _locale: en
        permanent: true
